<?php
use Drupal\Core\Site\Settings;

/**
 * Implements hook_cron().
 */
function tugboat_cron() {
  $tugboat_execute = \Drupal::service('tugboat.execute');
  $config = \Drupal::config('tugboat.settings');

  // Run on an interval that matches the length of the current lifetime.
  $lifetime_timestamp = $config->get('tugboat_sandbox_lifetime');
  if (REQUEST_TIME - $config->get('tugboat_cron', 0) > $lifetime_timestamp) {
    $config->get('tugboat_cron', REQUEST_TIME);

    $delete_older_than_timestamp = REQUEST_TIME - $lifetime_timestamp;

    $repo = $config->get('tugboat_repository_id');
    $return_data = array();
    $error_string = '';
    $success = $tugboat_execute->_tugboat_execute("ls previews repo=$repo", $return_data, $error_string);
    if (!$success) {
      \Drupal::logger('tugboat')->error('Unable to select sandboxes during cron run. Error from tugboat: @error', array('@error' => $error_string));
    }

    $delete_count = 0;
    foreach ($return_data as $sandbox) {
      // Delete if not a base (anchor) preview and it's past the expire date.
      if (!$sandbox['anchor'] && strtotime($sandbox['createdAt']) < $delete_older_than_timestamp) {
        $sandbox_id = $sandbox['id'];
        $return_data = array();
        $error_string = '';
        $success = $tugboat_execute->_tugboat_execute("delete $sandbox_id", $return_data, $error_string);
        if (!$success) {
        \Drupal::logger('tugboat')->error('Unable to delete individual sandbox during cron run. Error from tugboat: @error', array('@error' => $error_string));
        }
        else {
          $delete_count++;
        }
      }
    }

    if ($delete_count) {
      \Drupal::logger('tugboat')->notice('tugboat', 'Deleted @count demo sandboxes older than @date.', array('@count' => $delete_count, '@date' => format_date($delete_older_than_timestamp)));
    }
  }
}
