# Schema for the configuration files of the Tugboat module.

tugboat.settings:
  type: config_object
  label: 'Tugboat settings'
  mapping:
    tugboat_executable_path:
      type: string
      label: 'Add tugboat executable path'
    tugboat_repository_id:
      type: string
      label: 'Add tugboat repository id'
    tugboat_repository_base:
      type: string
      label: 'Add tugboat repository base'
    tugboat_sandbox_lifetime:
      type: string
      label: 'Add tugboat sandbox lifetime'
